routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('ordenes', 'OrdenController');

Route::post('/ticket', 'OrdenController@buscarTicket')->name('ticket');

Route::post('/revision/agregar', 'OrdenController@storeRevision')->name('revision.agregar');

Route::resource('revisions', 'RevisionController');

app/Models/Orden.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Orden
 * @package App\Models
 * @version November 12, 2017, 9:25 pm -05
 *
 * @property string nombres
 * @property string apellidos
 * @property string direccion
 * @property string serial
 * @property string observacion
 * @property string tiket
 */
class Orden extends Model
{
    use SoftDeletes;

    public $table = 'ordenes';
    

    protected $dates = ['deleted_at'];


    public $fillable = [
        'nombres',
        'apellidos',
        'direccion',
        'serial',
        'observacion',
        'tiket',
        'user_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'nombres' => 'string',
        'apellidos' => 'string',
        'direccion' => 'string',
        'serial' => 'string',
        'observacion' => 'string',
        'tiket' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'nombres' => 'required',
        'apellidos' => 'required',
        'direccion' => 'required',
        'serial' => 'required'
    ];


    public function user()
    {
        return $this->belongsTo('App\User');
    } 

    public function revisiones()
    {
        return $this->hasMany('App\Models\Revision');
    }

    
}

app/Http/Controllers/OrdenController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\AppBaseController;
use App\Http\Requests\CreateOrdenRequest;
use App\Http\Requests\CreateRevisionRequest;
use App\Http\Requests\UpdateOrdenRequest;
use App\Models\Orden;
use App\Models\Revision;
use App\Repositories\OrdenRepository;
use Flash;
use Illuminate\Http\Request;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class OrdenController extends AppBaseController
{
    /** @var  OrdenRepository */
    private $ordenRepository;

    public function __construct(OrdenRepository $ordenRepo)
    {
        $this->middleware('auth');
        $this->ordenRepository = $ordenRepo;
    }

    /**
     * Display a listing of the Orden.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->ordenRepository->pushCriteria(new RequestCriteria($request));
        $ordens = $this->ordenRepository->all();

        return view('ordens.index')
            ->with('ordens', $ordens);
    }

    /**
     * Show the form for creating a new Orden.
     *
     * @return Response
     */
    public function create()
    {
        return view('ordens.create');
    }

    /**
     * Store a newly created Orden in storage.
     *
     * @param CreateOrdenRequest $request
     *
     * @return Response
     */
    public function store(CreateOrdenRequest $request)
    {
        $input = $request->all();
        $input['tiket'] = rand();
        $input['user_id'] = auth()->id();

        $orden = $this->ordenRepository->create($input);

        Flash::success('Orden Registrada con el ticket Número: <b>'. $orden->tiket .' </b>');

        return redirect(route('ordenes.index'));
    }

    /**
     * Display the specified Orden.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($ticket)
    {
        $orden = Orden::where('tiket', $ticket)->first();

        if (empty($orden)) {
            Flash::error('Ticket número '. $ticket .' No encontrado');

            return redirect(route('home'));
        }

        return view('ordens.show')->with('orden', $orden);
    }

     public function buscarTicket(Request $request)
    {
        $orden = Orden::where('tiket', $request->ticket)->first();

        if (empty($orden)) {
            Flash::error('Ticket número <b>'. $request->ticket .'</b> No encontrado');

            return redirect(route('home'));
        }

        return view('ordens.show')->with('orden', $orden);
    }


    /**
     * Show the form for editing the specified Orden.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $orden = $this->ordenRepository->findWithoutFail($id);

        if (empty($orden)) {
            Flash::error('Orden no encontrada');

            return redirect(route('ordenes.index'));
        }

        return view('ordens.edit')->with('orden', $orden);
    }

    /**
     * Update the specified Orden in storage.
     *
     * @param  int              $id
     * @param UpdateOrdenRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateOrdenRequest $request)
    {
        $orden = $this->ordenRepository->findWithoutFail($id);

        if (empty($orden)) {
            Flash::error('Orden no encontrada');

            return redirect(route('ordenes.index'));
        }

        $input = $request->all();
        $input['user_id'] = auth()->id();

        $orden = $this->ordenRepository->update($input, $id);

        Flash::success('Orden actualizada.');

        return redirect(route('ordenes.index'));
    }

    /**
     * Remove the specified Orden from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $orden = $this->ordenRepository->findWithoutFail($id);

        if (empty($orden)) {
            Flash::error('Orden no encontrada');

            return redirect(route('ordenes.index'));
        }

        $this->ordenRepository->delete($id);

        Flash::success('Orden Eliminada.');

        return redirect(route('ordenes.index'));
    }

    public function storeRevision(CreateRevisionRequest $request)
    {
        $input = $request->all();
        $input['user_id'] = auth()->id();

        $revision = Revision::create($input);

        Flash::success('Revisión registrada correctamente.');

        return redirect(route('ordenes.show', [$revision->orden->tiket]));
    }
}

resources/views/ordens/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Orden
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-success">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'ordenes.store']) !!}

                        @include('ordens.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/ordens/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Orden
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($orden, ['route' => ['ordenes.update', $orden->id], 'method' => 'patch']) !!}

                        @include('ordens.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/ordens/fields.blade.php
<!-- Nombres Field -->
<div class="form-group col-sm-6">
    {!! Form::label('nombres', 'Nombres (cliente):') !!}
    {!! Form::text('nombres', null, ['class' => 'form-control']) !!}
</div>

<!-- Apellidos Field -->
<div class="form-group col-sm-6">
    {!! Form::label('apellidos', 'Apellidos (cliente):') !!}
    {!! Form::text('apellidos', null, ['class' => 'form-control']) !!}
</div>

<!-- Direccion Field -->
<div class="form-group col-sm-6">
    {!! Form::label('direccion', 'Dirección:') !!}
    {!! Form::text('direccion', null, ['class' => 'form-control']) !!}
</div>

<!-- Serial Field -->
<div class="form-group col-sm-6">
    {!! Form::label('serial', 'Serial:') !!}
    {!! Form::text('serial', null, ['class' => 'form-control']) !!}
</div>

<!-- Observacion Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('observacion', 'Observaciones:') !!}
    {!! Form::textarea('observacion', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Registrar', ['class' => 'btn btn-success']) !!}
    <a href="{!! route('ordenes.index') !!}" class="btn btn-default">Cancelar</a>
</div>

resources/views/ordens/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Lista de Ordenes</h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-success">
            <div class="box-body">
                    @include('ordens.table')
            </div>
        </div>
    </div>
@endsection

resources/views/ordens/revision-fields.blade.php
<input type="hidden" name="orden_id"  value="{{ $orden->id }}">

<!-- Pieza Afectada Field -->
<div class="form-group col-sm-6">
    <label for="pieza_afectada">Pieza Afectada:</label>
    <input type="text" name="pieza_afectada" class="form-control">
</div>

<!-- Pieza Remplazada Field -->
<div class="form-group col-sm-6">
    <label for="pieza_remplazada">Pieza Remplazada:</label>
    <input type="text" name="pieza_remplazada" class="form-control">
</div>

<!-- Observaciones Field -->
<div class="form-group col-sm-12 col-lg-12">
    <label for="observaciones">Observaciones:</label>
    <textarea name="observaciones" id="observaciones" class="form-control" rows="10"></textarea>
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    <button class="btn btn-warning"> <i class="fa fa-heartbeat"></i> Agregar Revisión</button>     
</div>

resources/views/ordens/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Orden / Ticket: {{ $orden->tiket }} 
             @if ( optional($orden->revisiones)->isEmpty() )
                <span class="label label-warning">Pendiente</span>
            @else
                <span class="label label-success">Revisada</span>
            @endif
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        @include('flash::message')
        <div class="box box-primary">            
            <div class="box-body">
                <div class="row" style="padding: 20px">
                    @include('ordens.show_fields')                    
                </div>
            </div>
        </div>
        @foreach ($orden->revisiones as $revision)
            <div class="box box-success">
                <div class="box-header">
                    <h3 class="box-title pull-left">
                        Revisión No:  
                        <b>{{ $loop->iteration }}</b>                   
                    </h3>
                    <h3 class="box-title pull-right">
                        {{ $revision->created_at->format('d-m-Y') }}
                        ({{ $revision->created_at->diffForHumans() }})
                    </h3>
                </div>
                <div class="box-body">
                    <div class="row" style="padding: 20px">
                        <table class="table table-bordered">
                            <tr>
                                <th>Id:</th>
                                <th>Pieza Afectada:</th>
                                <th>Pieza Remplazada:</th>
                            </tr>
                            <tr>
                                <td>{{ $revision->id }}</td>
                                <td>{!! $revision->pieza_afectada !!}</td>
                                <td>{!! $revision->pieza_remplazada !!}</td>
                            </tr>
                        </table>                               
                        <h4>Observaciones:</h4>
                        {{ $revision->observaciones }}
                        <h4>Técnico:</h4>
                        {{ $revision->user->name }}
                    </div>
                </div>
            </div>
        @endforeach             
        @if (auth()->user()->role == 'tecnico')
        <div class="box box-warning">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'revision.agregar']) !!}

                        @include('ordens.revision-fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
        @endif
    </div>
@endsection

resources/views/ordens/show_fields.blade.php
<table class="table table-bordered table-striped">
    <tr>
        <th>Id</th>
        <th>Ticket</th>
        <th>Nombre</th>
        <th>Apelldos</th>
    </tr>
    <tr>
        <td>{!! $orden->id !!}</td>
        <td>{!! $orden->tiket !!}</td>
        <td>{!! $orden->nombres !!}</td>
        <td>{!! $orden->apellidos !!}</td>
    </tr>
    <tr>
        <th>Dirección</th>
        <th>Serial</th>
        <th>Fecha de registro</th>
        <th>Última actualización</th>
    </tr>
    <tr>
        <td>{!! $orden->direccion !!}</td>
        <td>{!! $orden->serial !!}</td>
        <td>{!! $orden->created_at !!}</td>
        <td>{!! $orden->updated_at->diffForHumans() !!}</td>
    </tr>
</table>


<!-- Observacion Field -->
<div class="form-group">
    {!! Form::label('observacion', 'Observaciones:') !!}
    <p>{!! $orden->observacion !!}</p>
</div>


<!-- user At Field -->
<div class="form-group">
    {!! Form::label('user', 'Usuario que registra:') !!}
    <p>{!! $orden->user->name !!}</p>
</div>

resources/views/ordens/table.blade.php
<table class="table table-responsive" id="ordens-table">
    <thead>
        <tr>
            <th>Ticket</th>
            <th>Nombres</th>
            <th>Apellidos</th>
            <th>Estado</th>
            <th>Direccion</th>
            <th>Serial</th>
            <th colspan="3">Acciones</th>
        </tr>
    </thead>
    <tbody>
    @foreach($ordens as $orden)
        <tr>
            <td>{!! $orden->tiket !!}</td>
            <td>{!! $orden->nombres !!}</td>
            <td>{!! $orden->apellidos !!}</td>
            <td>
                @if ( optional($orden->revisiones)->isEmpty() )
                    <span class="label label-warning">Pendiente</span>
                @else
                    <span class="label label-success">Revisada</span>
                @endif
            </td>
            <td>{!! $orden->direccion !!}</td>
            <td>{!! $orden->serial !!}</td>
            <td>
                {!! Form::open(['route' => ['ordenes.destroy', $orden->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('ordenes.show', [$orden->tiket]) !!}" class='btn btn-default btn-sm'><i class="glyphicon glyphicon-eye-open"></i> Ver</a>
                    <a href="{!! route('ordenes.edit', [$orden->id]) !!}" class='btn btn-default btn-sm'><i class="glyphicon glyphicon-edit"></i> Editar</a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-sm', 'onclick' => "return confirm('Estas seguro?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>